version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - echo "Update OS"
      - echo "Install pip package for build"
      - pip3 install --upgrade pip
      - pip3 install -r requirements-build.txt
  build:
    commands:
      - echo "Packaging template"
      - export BUCKET=lambda-deployment-artifacts-us-east-1
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml